theme: jekyll-theme-minimal
title: MeV gamma-ray all sky 
description: This webpage describes a study of MeV gamma-ray all sky.

lsi: false
safe: true
source: [your repo's top level directory]
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
